# Generated by Django 4.2.6 on 2024-04-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Topic_to_learn',
        ),
    ]
