# Generated by Django 4.2.6 on 2024-04-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_tests_to_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests_to_do',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
